from __future__ import annotations

from typing import Any, Protocol


class IScanStore(Protocol):
    def load(self, name: str) -> dict[str, Any] | None: ...
    def save(self, name: str, data: dict[str, Any]) -> None: ...
    def list_all(self) -> list[dict[str, Any]]: ...
    def ensure_folders(self, name: str) -> None: ...
    def update_hardware_metrics(self, scan_name: str, duration_s: float) -> None: ...
