backlog = 128
ip = 127.0.0.1
port = 8080

error_page_filepath = /home/docteurbadluck/Desktop/3D_scanner/computer/webserver/webserv/srcs/start_server/internal/init_server/a_init_server_rules/5_external_tool/default_error.html
max_size_request_body = 104857600

list_allowed_method = GET POST DELETE

file_system_root = /3D_scanner  /home/docteurbadluck/Desktop/3D_scanner/computer/webserver/www

enable_directory_listing = true
default_filepath = index.html

enable_upload = true
upload_folder = /home/docteurbadluck/Desktop/3D_scanner/computer/webserver/www/upload
client_timeout = 30

session_timeout = 1
session_secure_only = false
max_sessions = 200
